### ISSUE TITLE
hr vimbundles, command not found. Readme or command needs update.

### ISSUE THREAD

**Issue by MichaelDimmitt** [hashrocket/dotmatrix#60] opened 2017-08-13 19:02 UTC
Hello, on a factory restored MacBook computer , 
note: mac using default bash terminal
## The problem,
The readme for dotmatrix states run:
```cd dotmatrix;```
```bin/install;```
Then 
```hr vimbundles;```

## The fix, (workaround for the problem)
When in dot-matrix directory,
Run the hr bin script:
```./hr/bin/hr;```

Now it seemed the hr command will be found in future use.

<b>Summary, perhaps ```bin/install;``` is not performing the install for hr command.</b>

#### Inside of ```#bin/install```
<b>Possible problem:</b> ```$PWD/hr/bin/hr autoinstall```

<b>Possible resolution:</b> ```./$PWD/hr/bin/hr autoinstall```
to actually run the script for autoinstall.

<hr>
Not a duplicate of #47

**Comment by plicjo** [comment] 2017-08-24 17:06
Did you restart your shell after running `bin/install`?

**Comment by MichaelDimmitt** [comment] 2017-09-04 15:33
@plicjo, apologies taking so long to respond.
Yep, I had tried restarting the shell. 
I think the solution needs to be coded and that the script is not being run. 

I can make a pull request if there is interest. 
To show how small the change would be. 
The big question, "will it actually make a difference?" 
That question will not be answered until the issue is able to be replicated by others.

The trouble, to replicate the issue you almost have to factory restore your computer.
Thereby making yourself a user with no preinstalled programmer tools.

**Comment by dkarter** [comment] 2017-09-04 22:21
@MichaelDimmitt thanks for opening this issue!

I noticed in your issue description that you spelled the command `hr vimbundles` which is not correct. The correct command is `hr vimbundle` (singular as opposed to plural). This may have been the cause for the `command not found` message you were seeing. 🙂

The solution we use to install Vim plugins has recently changed to Vim Plug (see #64). The issue you were experiencing was prior to that change. I recommend you get the latest dotmatrix and follow the instructions here https://github.com/hashrocket/dotmatrix/blob/master/README.md#vim-plugins to see if this issue is still replicatable.

The short of it is that you no longer need to use `hr vimbundle` instead you will be able to install plugins using `:PlugInstall` directly from Vim and `:PlugUpdate` to update your plugins.

I recently installed the latest dotmatrix (w/ Vim Plug) on a fresh Ubuntu machine and did not encounter any issues at all. If you are still able to replicate the problem on a fresh Virtual Box machine please let us know, otherwise feel free to close this issue.

**Comment by MichaelDimmitt** [comment] 2017-09-04 23:08
@dkarter, great idea. 
I believe the code was a fresh clone of dotmatrix because I was on a new programmer's computer.
I will check on the typo. 
However, I remember after running the install script  'hr vimbundle' was working.

**Comment by dkarter** [comment] 2017-09-22 13:12
Closing this issue for now. If you find a way to replicate the issue please let me know I'll reopen.

**Closed by dkarter** 2017-09-22 13:12 UTC

**Comment by MichaelDimmitt** [comment] 2017-09-23 01:23
@dkarter, thats fair. 
If I get my computer in the correct environment to replicate it many times. 
I will be back. 🙂  👍
